import json
import os
import tarfile
import zipfile
from pathlib import Path

import pytest

import rpt


def make_engagement(tmp_path, target="example.com", etype="ext") -> Path:
    base = tmp_path / "engagements"
    recon = base / target / etype / "recon"
    recon.mkdir(parents=True)
    (recon / "aad-raw.json").write_text('{"aad": true}')
    (recon / "dns-raw.json").write_text('{"dns": true}')
    (recon / "example_com_brief.md").write_text(
        "# Report\nGenerated by canvass v1.3.0\n## Summary\n"
    )
    (recon / "example_com_emails.txt").write_text("user@example.com\n")
    (recon / "example_com_run.log").write_text("canvass run complete\n")
    return base


def test_scan_finds_canvass(tmp_path):
    base = make_engagement(tmp_path)
    detections, skipped = rpt.scan_for_tools(base / "example.com", "ext")
    found = [d for d in detections if d.found]
    assert len(found) == 1
    assert found[0].tool_name == "canvass"
    assert found[0].version == "1.3.0"
    assert len(found[0].files) == 5
    assert skipped == []


def test_scan_missing_type_subdir(tmp_path):
    base = tmp_path / "engagements"
    (base / "example.com").mkdir(parents=True)
    detections, _ = rpt.scan_for_tools(base / "example.com", "ext")
    assert all(not d.found for d in detections)
    assert any("not found" in d.note for d in detections)


def test_scan_missing_tool_subdir(tmp_path):
    base = tmp_path / "engagements"
    (base / "example.com" / "ext").mkdir(parents=True)
    detections, _ = rpt.scan_for_tools(base / "example.com", "ext")
    missing = [d for d in detections if not d.found]
    assert any(d.tool_name == "canvass" for d in missing)


def test_scan_empty_subdir(tmp_path):
    base = tmp_path / "engagements"
    (base / "example.com" / "ext" / "recon").mkdir(parents=True)
    detections, _ = rpt.scan_for_tools(base / "example.com", "ext")
    missing = [d for d in detections if not d.found]
    assert any("no matching files" in d.note for d in missing)


def test_bundle_tar_gz(tmp_path, monkeypatch):
    base = make_engagement(tmp_path)
    monkeypatch.chdir(tmp_path)
    detections, skipped = rpt.scan_for_tools(base / "example.com", "ext")
    manifest = rpt.build_manifest("example.com", "20260423", "ext", detections, skipped)
    output = rpt.create_bundle("example.com", "20260423", "ext", detections, manifest, "tar.gz")
    assert output.exists()
    with tarfile.open(output) as tar:
        names = tar.getnames()
    assert any("manifest.json" in n for n in names)
    assert any("aad-raw.json" in n for n in names)


def test_bundle_zip(tmp_path, monkeypatch):
    base = make_engagement(tmp_path)
    monkeypatch.chdir(tmp_path)
    detections, skipped = rpt.scan_for_tools(base / "example.com", "ext")
    manifest = rpt.build_manifest("example.com", "20260423", "ext", detections, skipped)
    output = rpt.create_bundle("example.com", "20260423", "ext", detections, manifest, "zip")
    assert output.exists()
    with zipfile.ZipFile(output) as zf:
        names = zf.namelist()
    assert any("manifest.json" in n for n in names)
    assert any("aad-raw.json" in n for n in names)


def test_manifest_schema(tmp_path):
    base = make_engagement(tmp_path)
    detections, skipped = rpt.scan_for_tools(base / "example.com", "ext")
    manifest = rpt.build_manifest("example.com", "20260423", "ext", detections, skipped)
    assert manifest["bundle_spec_version"] == 1
    assert manifest["collector_version"] == rpt.__version__
    assert manifest["engagement"]["target_domain"] == "example.com"
    assert manifest["engagement"]["engagement_type"] == "ext"
    assert manifest["engagement"]["id"] == "example.com-ext-20260423"
    assert len(manifest["tools"]) == 1
    assert manifest["tools"][0]["name"] == "canvass"


def test_oversized_file_skipped(tmp_path, monkeypatch):
    base = make_engagement(tmp_path)
    monkeypatch.setattr(rpt, "MAX_FILE_BYTES", 10)
    detections, skipped = rpt.scan_for_tools(base / "example.com", "ext")
    assert any(s.reason for s in skipped)
    assert any("aad-raw.json" in s.path for s in skipped)


def test_output_exists_overwrites(tmp_path, monkeypatch):
    base = make_engagement(tmp_path)
    monkeypatch.chdir(tmp_path)
    stale = tmp_path / "example.com-ext-20260423.tar.gz"
    stale.write_text("old")
    stale_size = stale.stat().st_size
    detections, skipped = rpt.scan_for_tools(base / "example.com", "ext")
    manifest = rpt.build_manifest("example.com", "20260423", "ext", detections, skipped)
    output = rpt.create_bundle("example.com", "20260423", "ext", detections, manifest, "tar.gz")
    assert output.exists()
    assert output.stat().st_size != stale_size


def test_bundle_file_permissions(tmp_path, monkeypatch):
    base = make_engagement(tmp_path)
    monkeypatch.chdir(tmp_path)
    detections, skipped = rpt.scan_for_tools(base / "example.com", "ext")
    manifest = rpt.build_manifest("example.com", "20260423", "ext", detections, skipped)
    output = rpt.create_bundle("example.com", "20260423", "ext", detections, manifest, "tar.gz")
    assert oct(output.stat().st_mode)[-3:] == "600"
