import importlib
from pathlib import Path

import pytest

canvass = importlib.import_module("collectors.external.recon.canvass")


def make_recon_dir(tmp_path, files: dict[str, str]) -> Path:
    recon = tmp_path / "recon"
    recon.mkdir()
    for name, content in files.items():
        (recon / name).write_text(content)
    return recon


def test_finds_all_exact_files(tmp_path):
    make_recon_dir(tmp_path, {
        "aad-raw.json": "{}",
        "dns-raw.json": "{}",
        "cloud-raw.json": "{}",
        "crtsh-raw.json": "{}",
    })
    recon = tmp_path / "recon"
    matched = {}
    for role, pattern in canvass.FILES.items():
        hits = list(recon.glob(pattern))
        if hits:
            matched[role] = hits
    assert "aad_raw" in matched
    assert "dns_raw" in matched
    assert "cloud_raw" in matched
    assert "crtsh_raw" in matched


def test_finds_glob_files(tmp_path):
    make_recon_dir(tmp_path, {
        "example_com_brief.md": "# brief",
        "example_com_emails.txt": "user@example.com",
        "example_com_run.log": "done",
    })
    recon = tmp_path / "recon"
    assert list(recon.glob(canvass.FILES["brief_md"]))
    assert list(recon.glob(canvass.FILES["emails_txt"]))
    assert list(recon.glob(canvass.FILES["run_log"]))


def test_ignores_dotfiles(tmp_path):
    make_recon_dir(tmp_path, {
        ".hidden-raw.json": "{}",
        "aad-raw.json": "{}",
    })
    recon = tmp_path / "recon"
    hits = [f for f in recon.glob(canvass.FILES["aad_raw"]) if not f.name.startswith(".")]
    assert len(hits) == 1
    assert hits[0].name == "aad-raw.json"


def test_detect_version_finds_version(tmp_path):
    recon = make_recon_dir(tmp_path, {
        "example_com_brief.md": "# Report\nGenerated by canvass v1.2.7\n## Summary",
    })
    assert canvass.detect_version(recon) == "1.2.7"


def test_detect_version_case_insensitive(tmp_path):
    recon = make_recon_dir(tmp_path, {
        "example_com_brief.md": "Generated by Canvass V2.0.1\n",
    })
    assert canvass.detect_version(recon) == "2.0.1"


def test_detect_version_returns_none_when_missing(tmp_path):
    recon = make_recon_dir(tmp_path, {
        "example_com_brief.md": "# Report\nNo version info here.\n",
    })
    assert canvass.detect_version(recon) is None


def test_detect_version_returns_none_empty_dir(tmp_path):
    recon = tmp_path / "recon"
    recon.mkdir()
    assert canvass.detect_version(recon) is None
